// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjrmnfIlTynv5-tezVm1zvlcg6Svdhy5Q',
    appId: '1:496837605445:web:61c7840972a63003064b2c',
    messagingSenderId: '496837605445',
    projectId: 'test-flutter-app2',
    authDomain: 'test-flutter-app2.firebaseapp.com',
    databaseURL: 'https://test-flutter-app2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-flutter-app2.appspot.com',
    measurementId: 'G-D169115SXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlwIt4Ql7qraERV_AGaEXdD3iJgT4jCU',
    appId: '1:496837605445:android:e35f984336263885064b2c',
    messagingSenderId: '496837605445',
    projectId: 'test-flutter-app2',
    databaseURL: 'https://test-flutter-app2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-flutter-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNN27G7qhe_xvnurnophqBSJfr4IysVJM',
    appId: '1:496837605445:ios:c05810c7960b3c70064b2c',
    messagingSenderId: '496837605445',
    projectId: 'test-flutter-app2',
    databaseURL: 'https://test-flutter-app2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-flutter-app2.appspot.com',
    iosBundleId: 'com.example.handflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNN27G7qhe_xvnurnophqBSJfr4IysVJM',
    appId: '1:496837605445:ios:c05810c7960b3c70064b2c',
    messagingSenderId: '496837605445',
    projectId: 'test-flutter-app2',
    databaseURL: 'https://test-flutter-app2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-flutter-app2.appspot.com',
    iosBundleId: 'com.example.handflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjrmnfIlTynv5-tezVm1zvlcg6Svdhy5Q',
    appId: '1:496837605445:web:7b28cc6626b7ed74064b2c',
    messagingSenderId: '496837605445',
    projectId: 'test-flutter-app2',
    authDomain: 'test-flutter-app2.firebaseapp.com',
    databaseURL: 'https://test-flutter-app2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-flutter-app2.appspot.com',
    measurementId: 'G-260EYQXS7V',
  );
}
